// Auto-generated expanded data including Gents, Ladies, Kids across all categories
export const maxDateStr = "2026-06-02";

export const customersData = [
  {
    "name": "Vivek Reddy",
    "totalSpend": 14912.05,
    "purchaseCount": 6,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-01",
    "lastPurchase": "2026-03-13",
    "daysInactive": 81
  },
  {
    "name": "Pooja Gupta",
    "totalSpend": 16370.43,
    "purchaseCount": 7,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-01",
    "lastPurchase": "2026-05-18",
    "daysInactive": 15
  },
  {
    "name": "Anaya's Parent",
    "totalSpend": 31051.15,
    "purchaseCount": 19,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "KIDS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-01",
    "lastPurchase": "2026-05-27",
    "daysInactive": 6
  },
  {
    "name": "Vikram Sen",
    "totalSpend": 8026.79,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-01",
    "lastPurchase": "2026-03-07",
    "daysInactive": 87
  },
  {
    "name": "Meera Mishra",
    "totalSpend": 2831.46,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-01-02",
    "daysInactive": 151
  },
  {
    "name": "Sunita Singh",
    "totalSpend": 9789.68,
    "purchaseCount": 4,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-04-14",
    "daysInactive": 49
  },
  {
    "name": "Deepika Mishra",
    "totalSpend": 7839.72,
    "purchaseCount": 3,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-04-13",
    "daysInactive": 50
  },
  {
    "name": "Priya Pillai",
    "totalSpend": 34404.83,
    "purchaseCount": 15,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-05-23",
    "daysInactive": 10
  },
  {
    "name": "Priyanka Sen",
    "totalSpend": 14169.15,
    "purchaseCount": 6,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "LADIES",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-04-10",
    "daysInactive": 53
  },
  {
    "name": "Karan's Parent",
    "totalSpend": 25487.84,
    "purchaseCount": 16,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "KIDS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-05-24",
    "daysInactive": 9
  },
  {
    "name": "Neha Choudhury",
    "totalSpend": 17671.33,
    "purchaseCount": 8,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-02",
    "lastPurchase": "2026-05-18",
    "daysInactive": 15
  },
  {
    "name": "Deepika Bose",
    "totalSpend": 42526.92,
    "purchaseCount": 16,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-03",
    "lastPurchase": "2026-05-31",
    "daysInactive": 2
  },
  {
    "name": "Myra's Parent",
    "totalSpend": 20773.17,
    "purchaseCount": 12,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "KIDS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-03",
    "lastPurchase": "2026-04-27",
    "daysInactive": 36
  },
  {
    "name": "Divya Reddy",
    "totalSpend": 9132.07,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-03",
    "lastPurchase": "2026-05-01",
    "daysInactive": 32
  },
  {
    "name": "Meera Nair",
    "totalSpend": 32354.22,
    "purchaseCount": 15,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "LADIES",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-03",
    "lastPurchase": "2026-05-18",
    "daysInactive": 15
  },
  {
    "name": "Swati Verma",
    "totalSpend": 24076.75,
    "purchaseCount": 11,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-03",
    "lastPurchase": "2026-05-18",
    "daysInactive": 15
  },
  {
    "name": "Vikram Sharma",
    "totalSpend": 5477.54,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-04",
    "lastPurchase": "2026-03-02",
    "daysInactive": 92
  },
  {
    "name": "Meera Trivedi",
    "totalSpend": 9502.42,
    "purchaseCount": 3,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-04",
    "lastPurchase": "2026-05-22",
    "daysInactive": 11
  },
  {
    "name": "Kavita Iyer",
    "totalSpend": 20761.35,
    "purchaseCount": 10,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-04",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Rohan Sen",
    "totalSpend": 13122.91,
    "purchaseCount": 5,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-04",
    "lastPurchase": "2026-05-10",
    "daysInactive": 23
  },
  {
    "name": "Ananya Das",
    "totalSpend": 27766.69,
    "purchaseCount": 9,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-05",
    "lastPurchase": "2026-05-30",
    "daysInactive": 3
  },
  {
    "name": "Arjun Joshi",
    "totalSpend": 6119.74,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-05",
    "lastPurchase": "2026-04-24",
    "daysInactive": 39
  },
  {
    "name": "Sunita Reddy",
    "totalSpend": 10279.06,
    "purchaseCount": 4,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-06",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Ananya Gupta",
    "totalSpend": 8788.7,
    "purchaseCount": 4,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-06",
    "lastPurchase": "2026-04-14",
    "daysInactive": 49
  },
  {
    "name": "Shalini Singh",
    "totalSpend": 9715.92,
    "purchaseCount": 5,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "LADIES",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-06",
    "lastPurchase": "2026-04-21",
    "daysInactive": 42
  },
  {
    "name": "Siddharth's Parent",
    "totalSpend": 34924.93,
    "purchaseCount": 22,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "KIDS",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-01-06",
    "lastPurchase": "2026-05-31",
    "daysInactive": 2
  },
  {
    "name": "Diya's Parent",
    "totalSpend": 31032.08,
    "purchaseCount": 21,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "KIDS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-07",
    "lastPurchase": "2026-05-31",
    "daysInactive": 2
  },
  {
    "name": "Sunita Verma",
    "totalSpend": 3874.43,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-08",
    "lastPurchase": "2026-01-08",
    "daysInactive": 145
  },
  {
    "name": "Sanjay Iyer",
    "totalSpend": 6987.7,
    "purchaseCount": 3,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-08",
    "lastPurchase": "2026-04-29",
    "daysInactive": 34
  },
  {
    "name": "Anil Patel",
    "totalSpend": 7400.23,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-08",
    "lastPurchase": "2026-02-08",
    "daysInactive": 114
  },
  {
    "name": "Vivek Das",
    "totalSpend": 3296.8,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-09",
    "lastPurchase": "2026-01-09",
    "daysInactive": 144
  },
  {
    "name": "Suresh Nair",
    "totalSpend": 8420.75,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-09",
    "lastPurchase": "2026-01-26",
    "daysInactive": 127
  },
  {
    "name": "Kabir's Parent",
    "totalSpend": 23056.26,
    "purchaseCount": 14,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "KIDS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-09",
    "lastPurchase": "2026-05-27",
    "daysInactive": 6
  },
  {
    "name": "Rahul's Parent",
    "totalSpend": 22932.74,
    "purchaseCount": 14,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "KIDS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-09",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Sanjay Reddy",
    "totalSpend": 6393.36,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-10",
    "lastPurchase": "2026-02-04",
    "daysInactive": 118
  },
  {
    "name": "Neha Das",
    "totalSpend": 14329.79,
    "purchaseCount": 5,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-10",
    "lastPurchase": "2026-04-05",
    "daysInactive": 58
  },
  {
    "name": "Arjun Singh",
    "totalSpend": 5565.72,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-10",
    "lastPurchase": "2026-01-25",
    "daysInactive": 128
  },
  {
    "name": "Vivek Trivedi",
    "totalSpend": 5087.59,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-10",
    "lastPurchase": "2026-03-08",
    "daysInactive": 86
  },
  {
    "name": "Arjun Mehta",
    "totalSpend": 15228.56,
    "purchaseCount": 6,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-10",
    "lastPurchase": "2026-04-20",
    "daysInactive": 43
  },
  {
    "name": "Vikram Reddy",
    "totalSpend": 3257.17,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-11",
    "lastPurchase": "2026-01-11",
    "daysInactive": 142
  },
  {
    "name": "Rajesh Pandey",
    "totalSpend": 5789.49,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-11",
    "lastPurchase": "2026-05-10",
    "daysInactive": 23
  },
  {
    "name": "Sunita Pandey",
    "totalSpend": 2922.44,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-12",
    "lastPurchase": "2026-01-12",
    "daysInactive": 141
  },
  {
    "name": "Anil Kulkarni",
    "totalSpend": 7360.34,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-12",
    "lastPurchase": "2026-05-08",
    "daysInactive": 25
  },
  {
    "name": "Aditya's Parent",
    "totalSpend": 27684.18,
    "purchaseCount": 16,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "KIDS",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-01-12",
    "lastPurchase": "2026-05-29",
    "daysInactive": 4
  },
  {
    "name": "Sunita Rao",
    "totalSpend": 18270.12,
    "purchaseCount": 9,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "LADIES",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-01-12",
    "lastPurchase": "2026-05-26",
    "daysInactive": 7
  },
  {
    "name": "Sanjay Sen",
    "totalSpend": 11024.15,
    "purchaseCount": 4,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-13",
    "lastPurchase": "2026-05-20",
    "daysInactive": 13
  },
  {
    "name": "Manish Trivedi",
    "totalSpend": 4661.98,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-03-19",
    "daysInactive": 75
  },
  {
    "name": "Rajesh Singh",
    "totalSpend": 12002.45,
    "purchaseCount": 5,
    "channel": "Instagram",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-04-25",
    "daysInactive": 38
  },
  {
    "name": "Rajesh Bose",
    "totalSpend": 18717.24,
    "purchaseCount": 7,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-05-17",
    "daysInactive": 16
  },
  {
    "name": "Sanjay Kulkarni",
    "totalSpend": 6001.97,
    "purchaseCount": 3,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-04-05",
    "daysInactive": 58
  },
  {
    "name": "Vihaan's Parent",
    "totalSpend": 25884.47,
    "purchaseCount": 14,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "KIDS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-05-17",
    "daysInactive": 16
  },
  {
    "name": "Komal Reddy",
    "totalSpend": 21350.39,
    "purchaseCount": 9,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "LADIES",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-05-19",
    "daysInactive": 14
  },
  {
    "name": "Priya Iyer",
    "totalSpend": 10205.96,
    "purchaseCount": 4,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-15",
    "lastPurchase": "2026-05-27",
    "daysInactive": 6
  },
  {
    "name": "Divya Iyer",
    "totalSpend": 9167.85,
    "purchaseCount": 4,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-16",
    "lastPurchase": "2026-04-08",
    "daysInactive": 55
  },
  {
    "name": "Rajesh Iyer",
    "totalSpend": 7802.2,
    "purchaseCount": 3,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-16",
    "lastPurchase": "2026-05-21",
    "daysInactive": 12
  },
  {
    "name": "Sunita Iyer",
    "totalSpend": 3176.96,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-17",
    "lastPurchase": "2026-01-17",
    "daysInactive": 136
  },
  {
    "name": "Rajesh Das",
    "totalSpend": 4542.83,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-18",
    "lastPurchase": "2026-05-21",
    "daysInactive": 12
  },
  {
    "name": "Arjun Nair",
    "totalSpend": 7853.47,
    "purchaseCount": 3,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-19",
    "lastPurchase": "2026-05-03",
    "daysInactive": 30
  },
  {
    "name": "Vivek Verma",
    "totalSpend": 3343.56,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-20",
    "lastPurchase": "2026-01-20",
    "daysInactive": 133
  },
  {
    "name": "Deepika Pandey",
    "totalSpend": 9901.33,
    "purchaseCount": 4,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-20",
    "lastPurchase": "2026-03-18",
    "daysInactive": 76
  },
  {
    "name": "Sanjay Patel",
    "totalSpend": 5939.9,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-01-20",
    "lastPurchase": "2026-03-07",
    "daysInactive": 87
  },
  {
    "name": "Rajesh Kulkarni",
    "totalSpend": 10600.34,
    "purchaseCount": 4,
    "channel": "Instagram",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-21",
    "lastPurchase": "2026-05-24",
    "daysInactive": 9
  },
  {
    "name": "Pooja Joshi",
    "totalSpend": 6322.9,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-21",
    "lastPurchase": "2026-04-12",
    "daysInactive": 51
  },
  {
    "name": "Pooja Sen",
    "totalSpend": 6811.45,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-22",
    "lastPurchase": "2026-02-17",
    "daysInactive": 105
  },
  {
    "name": "Aarav's Parent",
    "totalSpend": 22434.11,
    "purchaseCount": 15,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "KIDS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-22",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Kriti Trivedi",
    "totalSpend": 12005.73,
    "purchaseCount": 6,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-22",
    "lastPurchase": "2026-05-17",
    "daysInactive": 16
  },
  {
    "name": "Priya Choudhury",
    "totalSpend": 8230.33,
    "purchaseCount": 3,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-23",
    "lastPurchase": "2026-04-11",
    "daysInactive": 52
  },
  {
    "name": "Sneha Joshi",
    "totalSpend": 8110.43,
    "purchaseCount": 4,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-23",
    "lastPurchase": "2026-04-05",
    "daysInactive": 58
  },
  {
    "name": "Swati Sen",
    "totalSpend": 7662.92,
    "purchaseCount": 3,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-23",
    "lastPurchase": "2026-02-27",
    "daysInactive": 95
  },
  {
    "name": "Sunita Kulkarni",
    "totalSpend": 11771.96,
    "purchaseCount": 5,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-24",
    "lastPurchase": "2026-05-30",
    "daysInactive": 3
  },
  {
    "name": "Suresh Gupta",
    "totalSpend": 13704.56,
    "purchaseCount": 5,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-24",
    "lastPurchase": "2026-05-10",
    "daysInactive": 23
  },
  {
    "name": "Meera Sharma",
    "totalSpend": 8859.02,
    "purchaseCount": 3,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-24",
    "lastPurchase": "2026-03-16",
    "daysInactive": 78
  },
  {
    "name": "Vivek Sharma",
    "totalSpend": 5535.13,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-24",
    "lastPurchase": "2026-05-14",
    "daysInactive": 19
  },
  {
    "name": "Deepika Kulkarni",
    "totalSpend": 15824.76,
    "purchaseCount": 7,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-25",
    "lastPurchase": "2026-05-07",
    "daysInactive": 26
  },
  {
    "name": "Pooja Patel",
    "totalSpend": 6606.29,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-25",
    "lastPurchase": "2026-05-08",
    "daysInactive": 25
  },
  {
    "name": "Pooja Mishra",
    "totalSpend": 4944.3,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-25",
    "lastPurchase": "2026-03-27",
    "daysInactive": 67
  },
  {
    "name": "Divya Sen",
    "totalSpend": 4687.34,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-25",
    "lastPurchase": "2026-03-01",
    "daysInactive": 93
  },
  {
    "name": "Anjali Sharma",
    "totalSpend": 25467.38,
    "purchaseCount": 11,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "LADIES",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-01-25",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Amit Verma",
    "totalSpend": 11526.43,
    "purchaseCount": 4,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-27",
    "lastPurchase": "2026-04-14",
    "daysInactive": 49
  },
  {
    "name": "Anil Verma",
    "totalSpend": 4990.9,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-28",
    "lastPurchase": "2026-04-08",
    "daysInactive": 55
  },
  {
    "name": "Deepika Pillai",
    "totalSpend": 7644.74,
    "purchaseCount": 3,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-28",
    "lastPurchase": "2026-03-24",
    "daysInactive": 70
  },
  {
    "name": "Swati Iyer",
    "totalSpend": 7369.35,
    "purchaseCount": 3,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-28",
    "lastPurchase": "2026-05-19",
    "daysInactive": 14
  },
  {
    "name": "Meera Mehta",
    "totalSpend": 5293,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-01-28",
    "lastPurchase": "2026-04-15",
    "daysInactive": 48
  },
  {
    "name": "Kavita Joshi",
    "totalSpend": 5070.02,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-29",
    "lastPurchase": "2026-05-17",
    "daysInactive": 16
  },
  {
    "name": "Vivek Pillai",
    "totalSpend": 3782.25,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-01-31",
    "lastPurchase": "2026-05-23",
    "daysInactive": 10
  },
  {
    "name": "Meera Kulkarni",
    "totalSpend": 6302.32,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-01",
    "lastPurchase": "2026-04-25",
    "daysInactive": 38
  },
  {
    "name": "Aishwarya Mehta",
    "totalSpend": 16254.24,
    "purchaseCount": 7,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-01",
    "lastPurchase": "2026-04-12",
    "daysInactive": 51
  },
  {
    "name": "Amit Bose",
    "totalSpend": 12808.27,
    "purchaseCount": 5,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-03",
    "lastPurchase": "2026-05-25",
    "daysInactive": 8
  },
  {
    "name": "Divya Choudhury",
    "totalSpend": 5867.69,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-04",
    "lastPurchase": "2026-04-18",
    "daysInactive": 45
  },
  {
    "name": "Amit Rao",
    "totalSpend": 4852.85,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-06",
    "lastPurchase": "2026-03-05",
    "daysInactive": 89
  },
  {
    "name": "Pooja Verma",
    "totalSpend": 5912.5,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-02-06",
    "lastPurchase": "2026-04-04",
    "daysInactive": 59
  },
  {
    "name": "Kavita Choudhury",
    "totalSpend": 6313.48,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-06",
    "lastPurchase": "2026-02-16",
    "daysInactive": 106
  },
  {
    "name": "Vikram Mehta",
    "totalSpend": 3228.74,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-07",
    "lastPurchase": "2026-02-07",
    "daysInactive": 115
  },
  {
    "name": "Kavita Mishra",
    "totalSpend": 5729.75,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-08",
    "lastPurchase": "2026-05-12",
    "daysInactive": 21
  },
  {
    "name": "Divya Patel",
    "totalSpend": 10165.58,
    "purchaseCount": 5,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-08",
    "lastPurchase": "2026-04-19",
    "daysInactive": 44
  },
  {
    "name": "Rohan Das",
    "totalSpend": 24651.93,
    "purchaseCount": 10,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-08",
    "lastPurchase": "2026-05-25",
    "daysInactive": 8
  },
  {
    "name": "Deepika Verma",
    "totalSpend": 6598.24,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-08",
    "lastPurchase": "2026-05-08",
    "daysInactive": 25
  },
  {
    "name": "Deepika Reddy",
    "totalSpend": 4758.37,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-09",
    "lastPurchase": "2026-02-16",
    "daysInactive": 106
  },
  {
    "name": "Sunita Sen",
    "totalSpend": 4730.53,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-11",
    "lastPurchase": "2026-04-13",
    "daysInactive": 50
  },
  {
    "name": "Sanjay Trivedi",
    "totalSpend": 6765.87,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-12",
    "lastPurchase": "2026-04-06",
    "daysInactive": 57
  },
  {
    "name": "Divya Das",
    "totalSpend": 7751.98,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-12",
    "lastPurchase": "2026-04-30",
    "daysInactive": 33
  },
  {
    "name": "Ritu Mishra",
    "totalSpend": 22971.12,
    "purchaseCount": 10,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "LADIES",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-13",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Anil Bose",
    "totalSpend": 5277.53,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-14",
    "lastPurchase": "2026-03-19",
    "daysInactive": 75
  },
  {
    "name": "Anil Joshi",
    "totalSpend": 8417.96,
    "purchaseCount": 3,
    "channel": "Instagram",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-16",
    "lastPurchase": "2026-04-27",
    "daysInactive": 36
  },
  {
    "name": "Arjun Kulkarni",
    "totalSpend": 16315.75,
    "purchaseCount": 6,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-16",
    "lastPurchase": "2026-05-30",
    "daysInactive": 3
  },
  {
    "name": "Sunita Trivedi",
    "totalSpend": 16266.14,
    "purchaseCount": 6,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-18",
    "lastPurchase": "2026-05-23",
    "daysInactive": 10
  },
  {
    "name": "Suresh Choudhury",
    "totalSpend": 6597.88,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-18",
    "lastPurchase": "2026-05-03",
    "daysInactive": 30
  },
  {
    "name": "Manish Mehta",
    "totalSpend": 3807.89,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-23",
    "lastPurchase": "2026-02-23",
    "daysInactive": 99
  },
  {
    "name": "Priya Mehta",
    "totalSpend": 4913.7,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-23",
    "lastPurchase": "2026-05-10",
    "daysInactive": 23
  },
  {
    "name": "Neha Mehta",
    "totalSpend": 4337.95,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-02-25",
    "lastPurchase": "2026-04-30",
    "daysInactive": 33
  },
  {
    "name": "Amit Nair",
    "totalSpend": 11950.78,
    "purchaseCount": 4,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-25",
    "lastPurchase": "2026-05-02",
    "daysInactive": 31
  },
  {
    "name": "Rohan Mishra",
    "totalSpend": 2643.13,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-26",
    "lastPurchase": "2026-02-26",
    "daysInactive": 96
  },
  {
    "name": "Priya Kulkarni",
    "totalSpend": 3776.99,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-26",
    "lastPurchase": "2026-02-26",
    "daysInactive": 96
  },
  {
    "name": "Suresh Das",
    "totalSpend": 3731.25,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-27",
    "lastPurchase": "2026-02-27",
    "daysInactive": 95
  },
  {
    "name": "Sunita Patel",
    "totalSpend": 17802.77,
    "purchaseCount": 7,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-27",
    "lastPurchase": "2026-05-26",
    "daysInactive": 7
  },
  {
    "name": "Amit Sen",
    "totalSpend": 13052.75,
    "purchaseCount": 5,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "ATHLETIC WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-02-28",
    "lastPurchase": "2026-05-18",
    "daysInactive": 15
  },
  {
    "name": "Nisha Kulkarni",
    "totalSpend": 7622.3,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "LADIES",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-02-28",
    "lastPurchase": "2026-05-07",
    "daysInactive": 26
  },
  {
    "name": "Arjun Mishra",
    "totalSpend": 2992.31,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-01",
    "lastPurchase": "2026-03-01",
    "daysInactive": 93
  },
  {
    "name": "Amit Kulkarni",
    "totalSpend": 3855.13,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-01",
    "lastPurchase": "2026-03-01",
    "daysInactive": 93
  },
  {
    "name": "Kavita Nair",
    "totalSpend": 8255.81,
    "purchaseCount": 4,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-01",
    "lastPurchase": "2026-05-07",
    "daysInactive": 26
  },
  {
    "name": "Pooja Reddy",
    "totalSpend": 5896.28,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-03-03",
    "lastPurchase": "2026-03-10",
    "daysInactive": 84
  },
  {
    "name": "Neha Sharma",
    "totalSpend": 3795.43,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-04",
    "lastPurchase": "2026-06-01",
    "daysInactive": 1
  },
  {
    "name": "Vivek Joshi",
    "totalSpend": 3310.5,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-05",
    "lastPurchase": "2026-03-05",
    "daysInactive": 89
  },
  {
    "name": "Rohan Patel",
    "totalSpend": 3755.5,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-07",
    "lastPurchase": "2026-03-07",
    "daysInactive": 87
  },
  {
    "name": "Manish Verma",
    "totalSpend": 3045.76,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-07",
    "lastPurchase": "2026-03-07",
    "daysInactive": 87
  },
  {
    "name": "Swati Nair",
    "totalSpend": 9913.02,
    "purchaseCount": 4,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-08",
    "lastPurchase": "2026-06-02",
    "daysInactive": 0
  },
  {
    "name": "Sanjay Das",
    "totalSpend": 7776.09,
    "purchaseCount": 3,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-08",
    "lastPurchase": "2026-05-22",
    "daysInactive": 11
  },
  {
    "name": "Sunita Choudhury",
    "totalSpend": 5126.29,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-03-08",
    "lastPurchase": "2026-05-12",
    "daysInactive": 21
  },
  {
    "name": "Manish Singh",
    "totalSpend": 2636.44,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-11",
    "lastPurchase": "2026-03-11",
    "daysInactive": 83
  },
  {
    "name": "Sanjay Singh",
    "totalSpend": 2664.96,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-11",
    "lastPurchase": "2026-03-11",
    "daysInactive": 83
  },
  {
    "name": "Aditi Pandey",
    "totalSpend": 14649.45,
    "purchaseCount": 5,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "LADIES",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-11",
    "lastPurchase": "2026-05-30",
    "daysInactive": 3
  },
  {
    "name": "Sanjay Joshi",
    "totalSpend": 5642.37,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-11",
    "lastPurchase": "2026-05-20",
    "daysInactive": 13
  },
  {
    "name": "Deepika Choudhury",
    "totalSpend": 5693.85,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-12",
    "lastPurchase": "2026-04-08",
    "daysInactive": 55
  },
  {
    "name": "Priya Sharma",
    "totalSpend": 4572.22,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-03-14",
    "lastPurchase": "2026-04-11",
    "daysInactive": 52
  },
  {
    "name": "Vikram Rao",
    "totalSpend": 2929.12,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-15",
    "lastPurchase": "2026-03-15",
    "daysInactive": 79
  },
  {
    "name": "Divya Mehta",
    "totalSpend": 6275.47,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-17",
    "lastPurchase": "2026-04-05",
    "daysInactive": 58
  },
  {
    "name": "Divya Gupta",
    "totalSpend": 5224.67,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-17",
    "lastPurchase": "2026-04-17",
    "daysInactive": 46
  },
  {
    "name": "Meera Bose",
    "totalSpend": 2637.21,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-18",
    "lastPurchase": "2026-03-18",
    "daysInactive": 76
  },
  {
    "name": "Anil Sen",
    "totalSpend": 2834.73,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-21",
    "lastPurchase": "2026-03-21",
    "daysInactive": 73
  },
  {
    "name": "Pooja Trivedi",
    "totalSpend": 7558.16,
    "purchaseCount": 3,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-21",
    "lastPurchase": "2026-05-17",
    "daysInactive": 16
  },
  {
    "name": "Neha Reddy",
    "totalSpend": 6778.12,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-23",
    "lastPurchase": "2026-05-06",
    "daysInactive": 27
  },
  {
    "name": "Sanjay Verma",
    "totalSpend": 2696.84,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-24",
    "lastPurchase": "2026-03-24",
    "daysInactive": 70
  },
  {
    "name": "Pooja Das",
    "totalSpend": 3838.47,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-24",
    "lastPurchase": "2026-03-24",
    "daysInactive": 70
  },
  {
    "name": "Sunita Pillai",
    "totalSpend": 6169.9,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "CASUAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-25",
    "lastPurchase": "2026-04-04",
    "daysInactive": 59
  },
  {
    "name": "Rajesh Gupta",
    "totalSpend": 3704.35,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-26",
    "lastPurchase": "2026-03-26",
    "daysInactive": 68
  },
  {
    "name": "Kavita Trivedi",
    "totalSpend": 3613.42,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-28",
    "lastPurchase": "2026-03-28",
    "daysInactive": 66
  },
  {
    "name": "Pooja Singh",
    "totalSpend": 3153.57,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-28",
    "lastPurchase": "2026-03-28",
    "daysInactive": 66
  },
  {
    "name": "Rohan Mehta",
    "totalSpend": 3766.53,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-30",
    "lastPurchase": "2026-03-30",
    "daysInactive": 64
  },
  {
    "name": "Ananya Verma",
    "totalSpend": 4080.83,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-03-31",
    "lastPurchase": "2026-04-09",
    "daysInactive": 54
  },
  {
    "name": "Neha Bose",
    "totalSpend": 3282.95,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-01",
    "lastPurchase": "2026-04-01",
    "daysInactive": 62
  },
  {
    "name": "Divya Singh",
    "totalSpend": 3120.48,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-04-01",
    "lastPurchase": "2026-04-01",
    "daysInactive": 62
  },
  {
    "name": "Deepika Joshi",
    "totalSpend": 3394.41,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-02",
    "lastPurchase": "2026-04-02",
    "daysInactive": 61
  },
  {
    "name": "Kavita Verma",
    "totalSpend": 5343.55,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-04",
    "lastPurchase": "2026-05-06",
    "daysInactive": 27
  },
  {
    "name": "Ananya Iyer",
    "totalSpend": 2835.56,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-07",
    "lastPurchase": "2026-04-07",
    "daysInactive": 56
  },
  {
    "name": "Ananya Joshi",
    "totalSpend": 3888.54,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-12",
    "lastPurchase": "2026-04-12",
    "daysInactive": 51
  },
  {
    "name": "Anil Nair",
    "totalSpend": 2652.59,
    "purchaseCount": 1,
    "channel": "Pinterest",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-04-13",
    "lastPurchase": "2026-04-13",
    "daysInactive": 50
  },
  {
    "name": "Amit Choudhury",
    "totalSpend": 5978.13,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-14",
    "lastPurchase": "2026-04-22",
    "daysInactive": 41
  },
  {
    "name": "Rohan Pillai",
    "totalSpend": 3393.59,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-15",
    "lastPurchase": "2026-04-15",
    "daysInactive": 48
  },
  {
    "name": "Neha Patel",
    "totalSpend": 9168.79,
    "purchaseCount": 3,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-04-16",
    "lastPurchase": "2026-05-24",
    "daysInactive": 9
  },
  {
    "name": "Amit Reddy",
    "totalSpend": 5045.78,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-04-16",
    "lastPurchase": "2026-04-28",
    "daysInactive": 35
  },
  {
    "name": "Ananya Sen",
    "totalSpend": 7757.05,
    "purchaseCount": 3,
    "channel": "Instagram",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-16",
    "lastPurchase": "2026-05-04",
    "daysInactive": 29
  },
  {
    "name": "Ananya Pillai",
    "totalSpend": 8367.58,
    "purchaseCount": 3,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": true,
    "firstPurchase": "2026-04-16",
    "lastPurchase": "2026-05-13",
    "daysInactive": 20
  },
  {
    "name": "Divya Nair",
    "totalSpend": 5056.39,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-04-18",
    "lastPurchase": "2026-04-30",
    "daysInactive": 33
  },
  {
    "name": "Manish Choudhury",
    "totalSpend": 3005.79,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-19",
    "lastPurchase": "2026-04-19",
    "daysInactive": 44
  },
  {
    "name": "Suresh Bose",
    "totalSpend": 5127.01,
    "purchaseCount": 2,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-20",
    "lastPurchase": "2026-05-12",
    "daysInactive": 21
  },
  {
    "name": "Kavita Reddy",
    "totalSpend": 3428.04,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-21",
    "lastPurchase": "2026-04-21",
    "daysInactive": 42
  },
  {
    "name": "Pooja Kulkarni",
    "totalSpend": 5221.35,
    "purchaseCount": 2,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-21",
    "lastPurchase": "2026-05-30",
    "daysInactive": 3
  },
  {
    "name": "Sanjay Bose",
    "totalSpend": 2999.04,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-04-22",
    "lastPurchase": "2026-04-22",
    "daysInactive": 41
  },
  {
    "name": "Sanjay Gupta",
    "totalSpend": 3687.73,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-24",
    "lastPurchase": "2026-04-24",
    "daysInactive": 39
  },
  {
    "name": "Divya Rao",
    "totalSpend": 5026.02,
    "purchaseCount": 2,
    "channel": "Pinterest",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-26",
    "lastPurchase": "2026-05-07",
    "daysInactive": 26
  },
  {
    "name": "Amit Iyer",
    "totalSpend": 3095.3,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-28",
    "lastPurchase": "2026-04-28",
    "daysInactive": 35
  },
  {
    "name": "Sanjay Nair",
    "totalSpend": 3724.81,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-04-30",
    "lastPurchase": "2026-04-30",
    "daysInactive": 33
  },
  {
    "name": "Manish Bose",
    "totalSpend": 2835.69,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-05-01",
    "lastPurchase": "2026-05-01",
    "daysInactive": 32
  },
  {
    "name": "Neha Pandey",
    "totalSpend": 6338.38,
    "purchaseCount": 2,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-05-02",
    "lastPurchase": "2026-05-14",
    "daysInactive": 19
  },
  {
    "name": "Vivek Iyer",
    "totalSpend": 5705.44,
    "purchaseCount": 3,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "ACCESSORIES",
    "hasReturn": false,
    "firstPurchase": "2026-05-02",
    "lastPurchase": "2026-05-17",
    "daysInactive": 16
  },
  {
    "name": "Anil Sharma",
    "totalSpend": 3339.22,
    "purchaseCount": 1,
    "channel": "Instagram",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-05-07",
    "lastPurchase": "2026-05-07",
    "daysInactive": 26
  },
  {
    "name": "Amit Trivedi",
    "totalSpend": 2717.88,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "EAST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-05-23",
    "lastPurchase": "2026-05-23",
    "daysInactive": 10
  },
  {
    "name": "Sanjay Rao",
    "totalSpend": 3072.72,
    "purchaseCount": 1,
    "channel": "TikTok",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-05-26",
    "lastPurchase": "2026-05-26",
    "daysInactive": 7
  },
  {
    "name": "Kavita Mehta",
    "totalSpend": 3758.94,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "WEST ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-05-27",
    "lastPurchase": "2026-05-27",
    "daysInactive": 6
  },
  {
    "name": "Neha Sen",
    "totalSpend": 3298.71,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "SOUTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": false,
    "firstPurchase": "2026-05-29",
    "lastPurchase": "2026-05-29",
    "daysInactive": 4
  },
  {
    "name": "Deepika Rao",
    "totalSpend": 3026.74,
    "purchaseCount": 1,
    "channel": "Direct",
    "zone": "NORTH ZONE",
    "segment": "GENTS",
    "category": "FORMAL WEAR",
    "hasReturn": true,
    "firstPurchase": "2026-05-30",
    "lastPurchase": "2026-05-30",
    "daysInactive": 3
  }
];

export const thresholdStats = [
  {
    "threshold": 30,
    "count": 104,
    "rate": 57.46
  },
  {
    "threshold": 45,
    "count": 80,
    "rate": 44.2
  },
  {
    "threshold": 60,
    "count": 53,
    "rate": 29.28
  },
  {
    "threshold": 75,
    "count": 39,
    "rate": 21.55
  },
  {
    "threshold": 90,
    "count": 24,
    "rate": 13.26
  }
];

export const channelsSummary = [
  {
    "name": "Instagram",
    "total": 49,
    "avgSpend": 9737.09
  },
  {
    "name": "TikTok",
    "total": 41,
    "avgSpend": 9283.28
  },
  {
    "name": "Pinterest",
    "total": 41,
    "avgSpend": 10489.98
  },
  {
    "name": "Direct",
    "total": 50,
    "avgSpend": 7109.86
  }
];

export const zonesSummary = [
  {
    "name": "WEST ZONE",
    "total": 47,
    "avgSpend": 10110.74
  },
  {
    "name": "SOUTH ZONE",
    "total": 45,
    "avgSpend": 8728.92
  },
  {
    "name": "EAST ZONE",
    "total": 43,
    "avgSpend": 8896.31
  },
  {
    "name": "NORTH ZONE",
    "total": 46,
    "avgSpend": 8538.4
  }
];

export const productSegmentsSummary = [
  {
    "name": "GENTS",
    "total": 153,
    "avgSpend": 6873.61
  },
  {
    "name": "LADIES",
    "total": 18,
    "avgSpend": 18132.82
  },
  {
    "name": "KIDS",
    "total": 10,
    "avgSpend": 26526.09
  }
];

export const productCategoriesSummary = [
  {
    "name": "FORMAL WEAR",
    "total": 105,
    "avgSpend": 6121.78
  },
  {
    "name": "ATHLETIC WEAR",
    "total": 25,
    "avgSpend": 14101.91
  },
  {
    "name": "CASUAL WEAR",
    "total": 35,
    "avgSpend": 11993.68
  },
  {
    "name": "ACCESSORIES",
    "total": 16,
    "avgSpend": 14262.56
  }
];

export const cohortSummary = [
  {
    "cohortMonth": "2026-01",
    "size": 85,
    "retention": [
      {
        "targetMonth": "2026-01",
        "active": 85,
        "rate": 100
      },
      {
        "targetMonth": "2026-02",
        "active": 39,
        "rate": 45.88
      },
      {
        "targetMonth": "2026-03",
        "active": 43,
        "rate": 50.59
      },
      {
        "targetMonth": "2026-04",
        "active": 44,
        "rate": 51.76
      },
      {
        "targetMonth": "2026-05",
        "active": 42,
        "rate": 49.41
      },
      {
        "targetMonth": "2026-06",
        "active": 5,
        "rate": 5.88
      }
    ]
  },
  {
    "cohortMonth": "2026-02",
    "size": 32,
    "retention": [
      {
        "targetMonth": "2026-02",
        "active": 32,
        "rate": 100
      },
      {
        "targetMonth": "2026-03",
        "active": 13,
        "rate": 40.63
      },
      {
        "targetMonth": "2026-04",
        "active": 15,
        "rate": 46.88
      },
      {
        "targetMonth": "2026-05",
        "active": 13,
        "rate": 40.63
      },
      {
        "targetMonth": "2026-06",
        "active": 1,
        "rate": 3.13
      }
    ]
  },
  {
    "cohortMonth": "2026-03",
    "size": 32,
    "retention": [
      {
        "targetMonth": "2026-03",
        "active": 32,
        "rate": 100
      },
      {
        "targetMonth": "2026-04",
        "active": 11,
        "rate": 34.38
      },
      {
        "targetMonth": "2026-05",
        "active": 8,
        "rate": 25
      },
      {
        "targetMonth": "2026-06",
        "active": 2,
        "rate": 6.25
      }
    ]
  },
  {
    "cohortMonth": "2026-04",
    "size": 23,
    "retention": [
      {
        "targetMonth": "2026-04",
        "active": 23,
        "rate": 100
      },
      {
        "targetMonth": "2026-05",
        "active": 7,
        "rate": 30.43
      },
      {
        "targetMonth": "2026-06",
        "active": 0,
        "rate": 0
      }
    ]
  },
  {
    "cohortMonth": "2026-05",
    "size": 9,
    "retention": [
      {
        "targetMonth": "2026-05",
        "active": 9,
        "rate": 100
      },
      {
        "targetMonth": "2026-06",
        "active": 0,
        "rate": 0
      }
    ]
  }
];
